### ISSUE TITLE
java.lang.NoClassDefFoundError: de/schlichtherle/license/LicenseManager

### ISSUE THREAD

**Issue by fanpan26** [fanpan26/tio-starters#1]
add dependency:
```
       <dependency>
            <groupId>de.schlichtherle.truelicense</groupId>
            <artifactId>truelicense-core</artifactId>
            <version>1.33</version>
            <scope>provided</scope>
        </dependency>
```
https://github.com/fanpan26/tio-starters/issues/1#issue-445279080
```
websocket samples throws error ：
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.fanpan26.tio.server.websocket.TioWebSocketServerInitializerConfiguration': Unsatisfied dependency expressed through field 'webSocketServerBootstrap'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webSocketServerBootstrap' defined in class path resource [com/fanpan26/tio/server/websocket/TioWebSocketServerAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.fanpan26.tio.server.websocket.TioWebSocketServerBootstrap]: Factory method 'webSocketServerBootstrap' threw exception; nested exception is java.lang.NoClassDefFoundError: de/schlichtherle/license/LicenseManager
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:584)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
```

**Comment by fanpan26** [comment]
https://gitee.com/zifangsky/LicenseDemo
